title: "Md. Khairul Basar"
logo: "/assets/images/Circle official.png"
description: "Passionate Industrial & Production Engineer with leadership experience in team projects. Skilled in Excel, VBA, data science, and machine learning. Focused on optimizing operations and supply chains."
theme: jekyll-theme-minimal
