title: Md. Khairul Basar
logo: /assets/images/Circle official.png
description: Passionate Industrial & Production Engineer with leadership experience in team projects. Skilled in Excel, VBA, data science, and machine learning. Focused on optimizing operations and supply chains.
#show_downloads: true
<div style="text-align: center; margin-top: 15px;">
    <a href="#education" class="btn">Education</a>
    <a href="#work-experience" class="btn">Work Experience</a>
    <a href="#projects" class="btn">Projects</a>
    <a href="#interests" class="btn">Interests</a>
</div>
theme: jekyll-theme-minimal
